version: '3.4'

services:
  gymbooster.api:
    image: ${DOCKER_REGISTRY-}gymboosterapi
    build:
      context: .
      dockerfile: GymBooster.Api/Dockerfile

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 32781:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example